const mockNews = [
    {
        id: 1,
        title: "Azerbaijan Signs Historic Energy Deal with European Union",
        description: "A landmark agreement to supply renewable energy to EU member states marks a turning point in regional diplomacy.",
        content: "In a ceremony held in Brussels, Azerbaijan's energy minister signed a comprehensive energy partnership deal with the European Union, promising to deliver up to 20 billion cubic meters of gas and significant green hydrogen capacity by 2030. The deal is seen as a major step in diversifying Europe's energy sources away from Russian dependency. Officials from both sides called it a 'generational opportunity' that would reshape the continent's energy landscape. Critics, however, warn of the environmental implications and call for stricter oversight of pipeline infrastructure.",
        image: "/img/news-1.svg",
        category: "Politics",
        author: "Lucy Hiddleston",
        timeAgo: "2 hours ago",
        readTime: "4min read",
        likes: 28,
        shares: 72,
        isBookmarked: false,
        isTrending: true,
        isBreaking: false,
        isLive: false,
        isEditorsPick: false
    },
    {
        id: 2,
        title: "Global Markets Surge as Fed Signals Rate Pause",
        description: "Wall Street closed at record highs after the Federal Reserve hinted it may hold interest rates steady through the summer.",
        content: "The S&P 500 gained 2.3% on Tuesday after Federal Reserve Chair Jerome Powell indicated the central bank is in no rush to raise rates further. Investors cheered the news, driving tech stocks to their highest levels since early 2022. Bond yields fell sharply in response. Economists remain divided on whether this signals the end of the tightening cycle or merely a temporary pause before further hikes. The dollar weakened against major currencies, providing relief to emerging market economies that have struggled under high borrowing costs.",
        image: "/img/news-2.svg",
        category: "Finance",
        author: "Marcus Brenly",
        timeAgo: "45 minutes ago",
        readTime: "3min read",
        likes: 134,
        shares: 210,
        isBookmarked: true,
        isTrending: true,
        isBreaking: true,
        isLive: false,
        isEditorsPick: false
    },
    {
        id: 3,
        title: "Scientists Discover New Deep-Sea Species Off Pacific Coast",
        description: "A research expedition has identified over 30 previously unknown marine organisms in the Mariana Trench region.",
        content: "A joint research team from the Scripps Institution of Oceanography and the University of Tokyo has catalogued 34 new species during a six-week deep-sea expedition. Among the discoveries are bioluminescent jellyfish, a new genus of isopods, and a translucent eel-like creature that appears to navigate entirely by magnetic field. The findings, published in Nature Marine Science, underscore how little is still known about the ocean's deepest habitats. Researchers warn that deep-sea mining operations could destroy these fragile ecosystems before they are fully studied.",
        image: "/img/news-3.svg",
        category: "Science",
        author: "Dr. Priya Nambiar",
        timeAgo: "5 hours ago",
        readTime: "6min read",
        likes: 89,
        shares: 43,
        isBookmarked: false,
        isTrending: false,
        isBreaking: false,
        isLive: false,
        isEditorsPick: true
    },
    {
        id: 4,
        title: "Champions League Final: Real Madrid vs Manchester City Preview",
        description: "Two of Europe's most storied clubs meet in Munich for what promises to be the most watched final in a decade.",
        content: "Saturday's Champions League final pits Erling Haaland's Manchester City against a resurgent Real Madrid side led by Kylian Mbappé. City are aiming for back-to-back European titles while Madrid seek a record-extending 15th. Tactical analysts expect a tight, high-pressure contest in the first half with both sides looking to exploit transitions. Injury concerns linger for City's midfield, with Kevin De Bruyne rated as doubtful. Ticket prices on the secondary market have surpassed €3,000, reflecting the enormous global appetite for the fixture.",
        image: "/img/news-4.svg",
        category: "Sports",
        author: "James Okafor",
        timeAgo: "1 hour ago",
        readTime: "5min read",
        likes: 312,
        shares: 540,
        isBookmarked: false,
        isTrending: true,
        isBreaking: false,
        isLive: true,
        isEditorsPick: false
    },
    {
        id: 5,
        title: "AI Breakthrough: New Model Passes Medical Licensing Exam with Near-Perfect Score",
        description: "A large language model developed by researchers has outperformed the average human physician on the USMLE, raising urgent questions about AI's role in healthcare.",
        content: "A research team at a leading Silicon Valley lab has announced that their latest AI model scored 96.2% on the United States Medical Licensing Examination, surpassing the average score of practicing physicians by more than 20 points. The system, trained on millions of clinical case studies and medical literature, demonstrated strong diagnostic reasoning across all tested specialties. Healthcare professionals have responded with a mix of enthusiasm and caution, noting that while AI can process data at scale, it cannot replicate the empathy and nuanced judgment required in patient care. Regulatory bodies are now in discussions over how to classify and oversee AI-assisted diagnosis tools.",
        image: "/img/news-5.svg",
        category: "Technology",
        author: "Sofia Reinholt",
        timeAgo: "30 minutes ago",
        readTime: "5min read",
        likes: 201,
        shares: 388,
        isBookmarked: false,
        isTrending: true,
        isBreaking: true,
        isLive: false,
        isEditorsPick: true
    },
];

export default mockNews;